import Footer from "@/pages/LandingPage/Footer/Footer";
import Navbar from "@/pages/LandingPage/Navbar/index";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });
import { ToastContainer, toast } from "react-toastify";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Navbar /> */}
        {children}
        {/* <Footer /> */}
        <ToastContainer />
      </body>
    </html>
  );
}
