import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Banner from "@/pages/LandingPage/Banner/banner";
import Companies from "@/pages/LandingPage/Companies/companies"
import Course from "@/pages/LandingPage/Courses/courses"
import Footer from "@/pages/LandingPage/Footer/footer"
import Navbar from "@/pages/LandingPage/Navbar/index";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app", 
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Navbar/>
      <Banner/>
      <Companies/>
      <Course/>
      <Footer/>
      {children}
      </body>
     
    </html>
  );
}
